services:
  - type: web
    name: descope-neon-authorize
    runtime: static
    # vite needs to be installed during build, so using the node environment as development
    buildCommand: NODE_ENV=development npm install && npm run build
    staticPublishPath: ./dist
    previews:
      generation: automatic # Enable service previews
    autoDeploy: false
    envVars:
      - key: NODE_ENV
        value: production

      - key: VITE_DESCOPE_PROJECT_ID
        sync: false # Configure your Descope Project ID in Render Dashboard

      - key: VITE_DATABASE_AUTHENTICATED_URL
        sync: false # Configure your NeonDB authenticated connection string in Render Dashboard
